apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-dev
  labels:
    release: prometheus-operator
spec:
  endpoints:
    - interval: 10s
      path: /actuator/prometheus
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: backend-metrics  # Matches the "instance" label of the target service.
      app.kubernetes.io/name: backend-metrics      # Matches the "name" label of the target service.